### ISSUE TITLE
Subdomains don't work.

### ISSUE THREAD

**Issue by ghost** [sindresorhus/is-port-reachable#4]
Right now I am working on a project that needs to check if the host address is working. Apparently if I use the host (eg http: // localhost) it works correctly, but when I want to check the subdomain (http: //subdomain.localhost), it doesn't work. Instead from the Chrome or Postman browser, this if the subdomain works.

**Comment by sindresorhus** [comment]
Seems to work for me: https://github.com/sindresorhus/is-port-reachable/blob/097d2492a537fb62f58532596ee5c7d69f3d0b9b/test.js#L19-L21
