### ISSUE TITLE
require() of ES Module not supported.

### ISSUE THREAD

**Issue by thomascouto** [sindresorhus/is-port-reachable#9]
> Instead change the require of index.js in C:\Users\thoma\Desktop\code\locacao\back-end\src\main\middlewares\net\connectionMiddleware.ts to a dynamic import() which is available in all CommonJS modules.

Test Code:

```
import { Request, Response, NextFunction } from 'express'
import env from '@/main/config/env'
import isPortReachable from 'is-port-reachable'

const checkConnection = async (request: Request, response: Response, next: NextFunction): Promise<void> => {
  const dbConnection = await isPortReachable(env.MONGO_PORT, { host: env.HOST })
  const adConnection = await isPortReachable(389, { host: '192.168.1.2' })

  console.log(dbConnection, adConnection)

  next()
}

export { checkConnection }
```

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by risharde** [comment]
It's a bit frustrating that this module does not support CommonJS. I cannot port over all of my app to ESM just for this to work.
